---
- hosts: db
  tasks:
    - name: update repopsirory
      shell: apt-get update

    - name: installing software properties
      shell: apt-get install software-properties-common -yf

    - name: add ppa repoository
      shell: add-apt-repository ppa:couchdb/stable -y


    - name: again update repository
      shell: apt-get update


    - name: install couchdb 
      shell: apt-get install couchdb -y

    - name: install curl 
      shell: apt-get install curl -y
      
    - name: adding new database with cli 
      command: curl -X PUT localhost:5984/sai
      
    - name: stop couchdb 
      shell: systemctl stop couchdb.service
    - name: change owner permission 
      shell: chown -R couchdb:couchdb /usr/share/couchdb /etc/couchdb /usr/bin/couchdb
      
    - name: change group permission 
      shell: chmod -R 0770 /usr/share/couchdb /etc/couchdb /usr/bin/couchdb
      
    - name: start couchdb 
      shell: systemctl start couchdb.service
      # Once CouchDB is installed, it should be running at localhost:5984. To verify, you can open up your terminal and type
      #  $ curl localhost:5984
